# xp-forge/inject

language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - wget 'http://xp-framework.net/downloads/releases/bin/setup' -O - | php
  - wget 'https://github.com/xp-framework/core/releases/download/v6.0.0alpha3/xp-rt-6.0.0alpha3.xar'
  - ls -1 *.xar > boot.pth
  - echo "[runtime]" >> xp.ini
  - echo "date.timezone=Europe/Berlin" >> xp.ini

script:
  - ./unittest src/test/php