# xp-forge/inject

language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - wget 'http://xp-framework.net/downloads/releases/bin/setup' -O - | php
  - wget 'https://github.com/xp-framework/core/releases/download/v6.0.0alpha3/xp-rt-6.0.0alpha3.xar'
  - ls -1 *.xar > boot.pth
  - echo "[runtime]" >> xp.ini
  - echo "date.timezone=Europe/Berlin" >> xp.ini

script:
  - ./unittest src/test/php

before_deploy:
  - export REL=`echo $TRAVIS_TAG | sed -e 's/^v//g'`
  - export MOD=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`
  - wget https://github.com/xp-framework/build/releases/download/v3.0.0alpha2/travis.xar
  - ./xp -cp travis.xar net.xp_framework.build.Travis . $MOD $REL
  - cat glue.json

deploy:
  provider: releases
  file:
    - xp-$MOD-$REL.xar
    - xp-$MOD-test-$REL.xar
    - glue.json
  skip_cleanup: true
  on:
    repo: $TRAVIS_REPO_SLUG
    tags: true
    all_branches: true
    php: 5.4
  api_key:
    secure: "YYY7M7a5/QbOSVT+D5TONLnsVjBL9IrSEecD510xHHviGsvBQXes9o+1I//2Hr3FvCHqFNQHLYiuQGS3SyCZvTXm4eUTeFbl6N/Z2ZBEFCVmCy0SzGC9qcjW8rtFm/bP9wWMDfepppNhD/OaLGnhg9YnNnrJb+PM+y7JgFfwWEg="
